theme: jekyll-theme-hacker
title: "OS_car's Pentesting Pathway"
description: "Penetration Testing | Hack The Box"

navigation:
  - title: "Home"
    url: "/"
  - title: "About Me"
    url: "/about"
  - title: "Projects"
    url: "/projects"
  - title: "Blog"
    url: "/blog"
